fujimoto-mio/techUP_study

松岡裕次郎/index_3_4.html, 松岡裕次郎/js/script.js
3-4の課題です。
HTMLとJSをフォルダに入れています。
確認お願い致します。
=> 課題3-4の提出です

武田侑大/3-10/index_3_10.html, 武田侑大/3-10/js/script.js, 武田侑大/3-9/index_3_9.html, 武田侑大/3-9/js/script.js
=> 武田 3-10 配列の削除

武田侑大/3-11/index_3_11.html, 武田侑大/3-11/js/script.js
=> 武田　課題3-11 内容確認

武田侑大/3-11/js/script.js
=> 武田課題3-11 mapでoutputを出力

武田侑大/3-11/js/script.js
Reverts fujimoto-mio/techUP_study#29
=> Revert "武田課題3-11 mapでoutputを出力"

松岡裕次郎/3-8/index_3_8.html, 松岡裕次郎/3-8/js/script.js
=> 松岡課題/3-8関数定義

松岡裕次郎/3-9/index_3_9.html, 松岡裕次郎/3-9/script.js
=> 松岡3-9課題/配列計算

武田侑大/3-13/index.html, 武田侑大/3-13/js/script.js
=> 武田課題3-13サイコロ

松岡裕次郎/3-10/index_3_10.html, 松岡裕次郎/3-10/script.js
=> 松岡/3-10課題/要素の変更

新村夕貴/level3_7/index_3_7.html
3-7の課題になります。ご確認のほどよろしくお願い致します。
=> 新村 3-7 条件分岐

新村夕貴/level3_9/index_3_9.html
３−９の課題になります。ご確認のほどよろしくお願い致します。
=> 新村　3−9　配列計算

新村夕貴/level3_10/index_3_10.html
3-10の課題になります。ご確認のほどよろしくお願い致します。
=> 新村 3-10 要素の変更

武田侑大/3-15/index.html, 武田侑大/3-15/js/script.js
=> 武田３－１５メソッドやクラスを使う

新村夕貴/level3_11/index_3_11.html
Level３−１１の課題になります。ご確認のほどよろしくお願い致します。
=> 新村 3-11 構文の使い方

松岡裕次郎/3-11/index_3_11.html, 松岡裕次郎/3-11/script.js
=> 松岡/3_11/構文の使い方

新村夕貴/level_3_12/index_3_12.html
３−１２の課題になります。ご確認のほどよろしくお願い致します。
=> 新村 3-12 オブジェクトの作り方　console.logの修正

松岡裕次郎/3-12/inedex_3_12.html, 松岡裕次郎/3-12/script.js
課題3-12オブジェクトの作り方完了致しましたので確認お願い致します。
=> 松岡/3_12/オブジェクトの作り方

新村夕貴/level3_13/index_3_13.html
３−１３の課題になります。ご確認のほどよろしくお願い致します。
=> 新村 3−13 配列とオブジェクトの組み合わせ

新村夕貴/level3_14/index_3_14.html
３−１４の課題になります。ご確認のほどよろしくお願い致します。
=> 新村 3-14 いろんなメソッド

松岡裕次郎/3-12/inedex_3_12.html, 松岡裕次郎/3-12/script.js, 松岡裕次郎/3-13/index_3_13.html, 松岡裕次郎/3-13/script.js
=> 松岡/ 3 13/配列とオブジェクトの組み合わせ

新村夕貴/level3_15/index_3_15.html
３−１５の課題提出になります。ご確認のほどよろしくお願い致します。
=> 新村 3-15 メソッドやクラスを使う log出力修正

武田侑大/3-16/index.html, 武田侑大/3-16/js/script.js
=> 3-16武田未完成確認

松岡裕次郎/3-14/index_3_14.html, 松岡裕次郎/3-14/script.js
=> 松岡/3-14/いろんなメソッド

武田侑大/3-17/index.html, 武田侑大/3-17/js/script.js
=> 3-17武田DOM総合課題

武田侑大/3-18/index.html, 武田侑大/3-18/js/script.js
=> 武田３－１８フォームの操作

松岡裕次郎/3-15/index_3_15.html, 松岡裕次郎/3-15/script.js
=> 松岡/3－15/メソッドやクラスを使う

武田侑大/3-21/index.html, 武田侑大/3-21/js/script.js
=> 武田３－２１canvas-2

武田侑大/3-22/index.html
=> 武田３－２２高解像度ディスプレイの対応

松岡裕次郎/3-16/index_3_16.html, 松岡裕次郎/3-16/script.js
=> 松岡/3-16/DOM

松岡裕次郎/3-17/index_3_17.html, 松岡裕次郎/3-17/script.js
=> 松岡/3-17/classlist(DOMの総合課題)

近内亜美/index_3_4.html
=> 近内　3_4 JavaScriptを学ぼう(JavaScript 1) 

武田侑大/3-23/css/style.css, 武田侑大/3-23/index.html, 武田侑大/3-23/js/timer.js
=> 武田３－２３カウントダウンタイマー

近内亜美/index_3_5.html
=> 近内亜美　Level3-5　JavaScript演算(JavaScript 2)

近内亜美/index_3_7.html
=>  近内亜美　　Level3-7 条件分岐

近内亜美/index_3_9.html
お疲れ様です。 Level3-9 配列計算を提出いたします。よろしくお願いします。
=> 近内亜美　 Level3-9 配列計算を提出いたします

加藤瑞希/index_3_16/index_3_16.css, 加藤瑞希/index_3_16/index_3_16.html
【質問】
おつかれさまです。
こちらの課題ですが、変更ボタンを押すと「0,1,2,3,4」と表示されてしまいます。
for文のどこを修正すれば「*10」になりますでしょうか。
=> 加藤_3_16 DOM

松岡裕次郎/3-18/index_3_18.html, 松岡裕次郎/3-18/script.js
=> 松岡/3-18/フォームの操作を理解しよう

近内亜美/index_3_10.html
=> 近内亜美　3-10 要素の変更

近内亜美/index_3_12.html
=> 近内亜美　Level3-12 オブジェクトの作り方

近内亜美/index_3_13.html
=> 近内亜美　Level3-13配列とオブジェクトの組み合わせ

近内亜美/index_3_14.html
Level3-14 いろんなメソッドの課題を提出いたします。
=> 近内亜美　Level3-14 いろんなメソッド

大野尚貴/level2-27/index.html
=> 大野 3_3_1　GitHubを使った作業

松岡裕次郎/3-20/index_3_20.html, 松岡裕次郎/3-20/script.js
=> 松岡/3-20/Canvas APIを利用しよう！(1)

松岡裕次郎/3-21/index_3_21.html, 松岡裕次郎/3-21/script.js
=> 松岡/3 21/Canvas APIを利用しよう！(2)

松岡裕次郎/3-21/index_3_21.html, 松岡裕次郎/3-21/script.js, 松岡裕次郎/3-22/index_3_22.html, 松岡裕次郎/3-22/script.js
=> 松岡/3 22/高解像度ディスプレイの対応

近内亜美/index_3_15 .html
=> 近内亜美　Level3-15 メソッドやクラスを使う

近内亜美/index_3_16.html
=> 近内亜美　Level3-16 DOM(Document Object Model)

大野尚貴/index_3_5.html/index_3_5.html
[数値変換 いろいろな計算方法]、 [インクリメント/デクリメントについて] の内容を確認するために、１つにまとめて実行しました！
=> 大野　3-5　JavaScript演算(JavaScript 2)

大野尚貴/index_3_7.html/source.html
=> 大野尚貴　3-7 条件分岐

大野尚貴/index_3_8.html/source.html
=> 大野尚貴3-8 関数定義

大野尚貴/index_3_9.html/source.html
=> 大野尚貴3-9 配列計算

武田侑大/6-2/index.php
=> 武田課題６－２日にち

大野尚貴/index_3_10.html/source.html
=> 大野尚貴3-10 要素の変更

大野尚貴/index_3_12.html/source.html
=> 大野尚貴3-12 オブジェクトの作り方

武田侑大/6-3/index.php, 武田侑大/6-3/member.csv
=> 武田６－３php演習

大野尚貴/index_3_13.html/source.html
=> 大野尚貴3-13配列とオブジェクトの組み合わせ

大野尚貴/index_3_14.html/source.html
=> 大野尚貴3-14 いろんなメソッド

武田侑大/6-4/index.php
=> 武田６－４cookie

松岡裕次郎/6-3/index.php, 松岡裕次郎/6-3/member.csv
=> 松岡/6-3/phpの演習をしよう!

近内亜美/index_3_18.html
=> 近内　Level3-18 フォームの操作を理解しよう！

松岡裕次郎/6-2/index.php, 松岡裕次郎/6-3/index.php, 松岡裕次郎/6-3/member.csv, 松岡裕次郎/6-4/index.php
=> 松岡/6 4/オブジェクト＆クラス

近内亜美/index_3_20 .html
=> 近内　Level3-20 Canvas APIを利用しよう！(1)

大野尚貴/index_3_15.html/source.html, 大野尚貴/index_3_16.html/source.html
=> 大野3-16 DOM

Sample/app/Http/Controllers/TaskController.php, Sample/app/Models/Task.php, Sample/config/database.php, Sample/database/migrations/2022_12_11_210241_create_tasks_table.php, Sample/resources/views/tasks/edit.blade.php, Sample/resources/views/tasks/index.blade.php, Sample/routes/web.php
７−６の課題を提出いたします。ご確認のほどよろしくお願い致します。
=> 新村 7-6 PDOオブジェクト

近内亜美/index_3_21.html
=> 近内　Level3-21 Canvas APIを利用しよう！(2)

近内亜美/index_3_22 .html
=> 近内　Level3-22 高解像度ディスプレイの対応

大野尚貴/index_3_17.html/source.html, 大野尚貴/index_3_17.html/todolist.js
=> 大野尚貴3-17 classList (DOM総合課題)

大野尚貴/index_3_18.html/source.html
=> 3-18 フォームの操作を理解しよう！

大野尚貴/index_3_20.html/source.html
=> 3-20大野 Canvas APIを利用しよう！(1)

松岡裕次郎/7-1/7-1.txt
=> 松岡/7-1/mysql

Sample/app/Http/Controllers/ApiSample.php, Sample/routes/api.php
=> 新村 8-1 API

大野尚貴/index_3_21.html/source.html
=> 大野3-21 Canvas APIを利用しよう！(2)

大野尚貴/index_3_22.html/source.html
=> 大野尚貴3-22 高解像度ディスプレイの対応

近内亜美/index_3_23/index.html, 近内亜美/index_3_23/style.css, 近内亜美/index_3_23/time.js
=> 近内　Level3-23 Javascript総合課題

大野尚貴/index_3_23.html/source.html, 大野尚貴/index_3_23.html/style.css, 大野尚貴/index_3_23.html/time.js
=> 大野尚貴3_23Javascript総合課題

松岡裕次郎/7-2/sample2.txt
=> 松岡/7-2/テーブル作成

Sample/app/Console/Commands/BirthdayMail.php, Sample/app/Console/Kernel.php, Sample/app/Http/Controllers/ApiTestController.php, Sample/app/Jobs/sendmail.php, Sample/app/Mail/SampleMail.php, Sample/database/migrations/2023_01_12_142823_create_jobs_table.php, Sample/database/migrations/2023_01_12_145642_add_user_is_table.php, Sample/database/migrations/2023_01_12_161703_create_jobs_table.php, Sample/routes/api.php
php artisan make:controller ApiTestController でファイルを作成しようとすると
Could not open input file: artisan make:controller とでてくるエラーになります。
操作履歴が以下になります。
Sample % history
1224  php artisan make:controllers ApiTestController
1225  php artisan migrate
1226  php artisan queue:table
1227  php artisan migrate
1228  php artisan make:controller ApiTestController
1229  php artisan make:migration
1230  php artisan list
1231  cd app/Http/Controllers
1232  php artisan make:controller ApiTestController
1233  cd .
1234  cd ./
1235  cd ~/
1236  cd Sample
1237  php artisan serve
1238  php artisan make:controller ApiTestController -m
1239  php artisan make:controller ApiTestController
ご確認のほどよろしくお願いいたします。
=> 新村 8-2 非同期＆バッチ処理

Sample/shellscript.sh
８−３の課題を提出いたします。お時間のよろしい時にご確認のほどよろしくお願いいたします。
=> 新村 8-3 コマンドライン

61_yanagi_serika/3-5/index.html, 61_yanagi_serika/3-5/js/script.js
=> 柳 3_５ Javascriptの演算

79_sonoyama_ryouga/level3_4/index_3_4.html
3_4 JavaScriptを学ぼう！ の提出です。確認をお願い致します。
=> 園山 level.3_４ JavaScriptを学ぼう！

79_sonoyama_ryouga/Level3_7/index3_7.html
=> 園山　Level3_7　条件分岐　の提出

79_sonoyama_ryouga/level3_9/index3_9.html
Level3-9 配列計算　が完了しましたので、確認をお願い致します。
=> 園山　Level3-9 配列計算　の提出

79_sonoyama_ryouga/level3_10/index3_10.html
Level3-10 要素の変更　が完了しましたので、確認をお願い致します。
=> 園山　Level3-10 要素の変更　の提出

79_sonoyama_ryouga/level3_10/index3_10.html, 79_sonoyama_ryouga/level3_11/index3_11.html
Level3-11　構文の使い方　が完了しましたので、確認をお願い致します。
=> 園山　Level3-11　構文の使い方　の提出

大野尚貴/Level6-2/index.php, 大野尚貴/index_4_3.html/source.html, 大野尚貴/p1-1/index.php
=> 大野P-2. phpの基本を書いていこう!

79_sonoyama_ryouga/level3_12/index3_12.html
Level3-12 オブジェクトの作り方　が完了しましたので、確認をお願い致します。
=> 園山　Level3-12 オブジェクトの作り方　の提出

79_sonoyama_ryouga/level3_12/index3_12.html, 79_sonoyama_ryouga/level3_13/index3_13.html
13 配列とオブジェクトの組み合わせ　が完了しましたので、確認をお願い致します。
=> 園山　13 配列とオブジェクトの組み合わせ　の提出

79_sonoyama_ryouga/level3_12/index3_12.html, 79_sonoyama_ryouga/level3_13/index3_13.html, 79_sonoyama_ryouga/level3_14/index3_14.html
Level3-14 いろんなメソッド　が完了しましたので、確認をお願い致します。
=> 園山　Level3-14 いろんなメソッド　の提出

66_takahashi_mio/level3-4(2)/.vscode/index.html, 66_takahashi_mio/level3-4(2)/.vscode/sample.js, 66_takahashi_mio/level3-4(2)/index_3_4.html, 66_takahashi_mio/level3-4(2)/sample.js
外部読み込みでファイルを追加し、ブラウザで表示確認済みです。3-4のファイルに3-4(2)が入っています。3-4空のファイルが消せなかったです。
=> takahashi3-4課題修正

大野尚貴/Level6-3/index.php, 大野尚貴/Level6-3/member.csv
=> 大野P-3. phpの演習をしよう!

79_sonoyama_ryouga/level3_15/index3_15.html
Level3-15 メソッドやクラスを使う　の課題はこうゆうことで間違い無いでしょうか？
確認をお願い致します。
=> 園山　Level3-15 メソッドやクラスを使う　の提出

79_sonoyama_ryouga/level3_16/index3_16.html
Level3-16 DOM(Document Object Model)　が完了しましたが、こういうことで間違い無いでしょうか？
確認をお願い致します。
=> 園山　Level3-16 DOM(Document Object Model)　の提出

106_kinbara/3-8/index3-8.html, 106_kinbara/3-8/js/script.js
=> 金原/3-8/関数定義

大野尚貴/Level6-4/index.php
=> 大野P-4. オブジェクト＆クラス

106_kinbara/3-9/index3-9.html, 106_kinbara/3-9/js/script.js
=> 金原/3-9/配列計算

106_kinbara/3-10/index3-10.html, 106_kinbara/3-10/js/script.js, 106_kinbara/3-9/index3-9.html, 106_kinbara/3-9/js/script.js
=> 金原/3-10/要素の変更

66_takahashi_mio/level3-8/index_3_8.html
=> 高橋/3-8/関数定義

66_takahashi_mio/level3-9/index_3_9.html
=> 高橋/3-9/配列計算

118_tezuka_saki/L3-4~7/L3-4/index_3_4.html, 118_tezuka_saki/L3-4~7/L3-4/script.js, 118_tezuka_saki/L3-4~7/L3-5/index_3_5.html, 118_tezuka_saki/L3-4~7/L3-5/script.js, 118_tezuka_saki/L3-4~7/L3-7/index_3_7.html, 118_tezuka_saki/L3-4~7/L3-7/script.js
=> 手塚 3_4~7 JavaScriptを学ぼう！~条件分岐

106_kinbara/3-11/index3-11.html, 106_kinbara/3-11/js/script.js
3-11 課題完了致しました。ご確認の程宜しくお願いいたします。
=> 金原/3-11/構文の使い方

106_kinbara/3-12/index3-12.html, 106_kinbara/3-12/js/script.js
=> 金原/3-12/オブジェクトの作り方

79_sonoyama_ryouga/level3_16/index3_16.html
Level3-16 DOM(Document Object Model)　の修正が終わりましたので確認のほどお願い致します。
=> 園山　Level3-16 DOM(Document Object Model)　修正

106_kinbara/3-13/index3-13.html, 106_kinbara/3-13/js/script.js, 106_kinbara/3-14/index3-14.html, 106_kinbara/3-14/js/script.js
=> 金原/3-14/いろんなメゾット

66_takahashi_mio/level3-12-14/index_3_12.html, 66_takahashi_mio/level3-12-14/index_3_13.html, 66_takahashi_mio/level3-12-14/index_3_14.html
3-12　オブジェクトの作り方、3-13 配列とオブジェクトの組み合わせ、3-14 いろんなメソッド
３つ提出させていただきます。
=> 高橋/3-12-13-14/課題

113_nagao_yuuki/P4-1. オブジェクト指向を覚える－１ 課題提出/index.php, 113_nagao_yuuki/P4-1. オブジェクト指向を覚える－１ 課題提出/php-7-answer.txt
=> 長尾P4-1. オブジェクト指向を覚える－１ 課題提出

大野尚貴/Level7-2/level7_2_table_study.sql
=> 大野P-5. MySQL接続しよう！

79_sonoyama_ryouga/level3_17/index3_17.html, 79_sonoyama_ryouga/level3_17/todolist.js
Level3-17 classList (DOM総合課題)　が完了したため、確認をお願い致します。
=> 園山　Level3-17 classList (DOM総合課題)　の提出

79_sonoyama_ryouga/level3_16/index3_16.html, 79_sonoyama_ryouga/level3_17/index3_17.html, 79_sonoyama_ryouga/level3_17/todolist.js, 79_sonoyama_ryouga/level3_18/index3_18.html
Level3-18 フォームの操作を理解しよう！が完了しましたので、確認をお願い致します。
=> 園山　Level3-18 フォームの操作を理解しよう！　の提出

106_kinbara/3-15/index3-15.html, 106_kinbara/3-15/js/script.js
課題完了致しましたが、課題１と課題２を続けてVScodeに記入するとエラーが出ます。別々のファイルに保存するべきでしょうか。
=> 金原/3-15/メゾットやクラスを使う

66_takahashi_mio/level3-15/index.html
=> 高橋/3-15/メゾットやクラスを使う

118_tezuka_saki/L3-8~10/L3-10/index_3_10.html, 118_tezuka_saki/L3-8~10/L3-10/script.js, 118_tezuka_saki/L3-8~10/L3-8/index_3_8.html, 118_tezuka_saki/L3-8~10/L3-8/script.js, 118_tezuka_saki/L3-8~10/L3-9/index_3_9.html, 118_tezuka_saki/L3-8~10/L3-9/script.js
=> 手塚 L3-8~10 関数定義

118_tezuka_saki/L3-11~12/L3-11/index_3_11.html, 118_tezuka_saki/L3-11~12/L3-11/script.js, 118_tezuka_saki/L3-11~12/L3-12/index_3_12.html, 118_tezuka_saki/L3-11~12/L3-12/script.js
L3_11-12の課題を提出いたします。
ご確認の程よろしくお願い致します。
=> 手塚 L3_11-12 構文の使い方

加藤瑞希/index_3_30/index_3_30.html, 加藤瑞希/index_3_30/style.css
おつかれさまです！
L3−30課題を提出させていただきます！
=> L3-30 加藤瑞希　jQuery課題提出

79_sonoyama_ryouga/leve3_20/index3_20.html
Level3-20 Canvas APIを利用しよう！(1)　が完了したため、確認をお願い致します。
=> 園山　Level3-20 Canvas APIを利用しよう！(1)　の提出

79_sonoyama_ryouga/leve3_20/index3_20.html, 79_sonoyama_ryouga/level3_21/index3_21.html
Level3-21 Canvas APIを利用しよう！(2)　が完了したため、確認をお願い致します。
=> 園山　 Level3-21 Canvas APIを利用しよう！(2)　の提出

118_tezuka_saki/L3-13~15/L3-13/index_3_13.html, 118_tezuka_saki/L3-13~15/L3-13/script.js, 118_tezuka_saki/L3-13~15/L3-14/index_3_14.html, 118_tezuka_saki/L3-13~15/L3-14/script.js, 118_tezuka_saki/L3-13~15/L3-15/L3-15-1/index_3_15.html, 118_tezuka_saki/L3-13~15/L3-15/L3-15-1/script.js, 118_tezuka_saki/L3-13~15/L3-15/L3-15-2/index_3_15.html, 118_tezuka_saki/L3-13~15/L3-15/L3-15-2/script.js
L3-13~15を提出致します。
ご確認の程、よろしくお願い致します。
=> 手塚 L3-13~15 配列とオブジェクトの組み合わせ

79_sonoyama_ryouga/level3_22/index3_22.html, 79_sonoyama_ryouga/level3_23/css/style.css, 79_sonoyama_ryouga/level3_23/index.html, 79_sonoyama_ryouga/level3_23/js/time.js
Level3-23 Javascript総合課題　が完了したため、確認をお願い致します。
=> 園山　Level3-23 Javascript総合課題　の提出

118_tezuka_saki/L3-16~17/L3-16/index_3_16.html, 118_tezuka_saki/L3-16~17/L3-16/script.js, 118_tezuka_saki/L3-16~17/L3-17/index_3_17.html, 118_tezuka_saki/L3-16~17/L3-17/script.js
L3-16~17を提出させて頂きます。
ご確認の程宜しくお願い致します。
=> 手塚 3-16~17 DOM

118_tezuka_saki/L3-18~22/L3-18/index_3_18.html, 118_tezuka_saki/L3-18~22/L3-18/script.js, 118_tezuka_saki/L3-18~22/L3-20/index_3_20.html, 118_tezuka_saki/L3-18~22/L3-20/script.js, 118_tezuka_saki/L3-18~22/L3-21/index_3_21.html, 118_tezuka_saki/L3-18~22/L3-21/script.js, 118_tezuka_saki/L3-18~22/L3-22/index_3_22.html, 118_tezuka_saki/L3-18~22/L3-22/script.js
=> 手塚 3_18-22 フォームの操作を理解しよう！

118_tezuka_saki/L3-23/index.html, 118_tezuka_saki/L3-23/style.css, 118_tezuka_saki/L3-23/time.js
=> 手塚 3_23 Javascript総合課題

117_sudou_taisei/index_3_4.html
お疲れ様です。
level3-4 　JavaScriptを学ぼう　課題提出いたします
ご確認の程、よろしくお願いいたします。
=> level3-4 須藤大晴　JavaScriptを学ぼう課題提出

79_sonoyama_ryouga/p1-1/index.php
P1-1. PHP導入 開発環境をととのえよう！(XAMPP)　が完了したため、確認をお願い致します。
=> 園山　P1-1. PHP導入 開発環境をととのえよう！(XAMPP)　の提出

79_sonoyama_ryouga/level6-2/index.php, 79_sonoyama_ryouga/p1-1/index.php
P-2. phpの基本を書いていこう!　が完了したため、確認をお願い致します。
=> 園山　P-2. phpの基本を書いていこう!　の提出

117_sudou_taisei/index_3_5.html
Level3-5 課題提出いたします
ご確認の程、よろしくお願いいたします
=> 須藤大晴　Level3-5課題提出

106_kinbara/3-16/3-16.html
課題ですが、10のかけ方、表示方法がうまくいきません。
考え方はあっていますでしょうか。
=> 金原/3-16/DOM

118_tezuka_saki/L6-1~4/L6-2/index.php, 118_tezuka_saki/L6-1~4/L6-3/index.php, 118_tezuka_saki/L6-1~4/L6-3/member.csv, 118_tezuka_saki/L6-1~4/L6-4/index.php, 118_tezuka_saki/L6-1~4/P1-1/index.php
=> 手塚 6_1~4 PHP導入

106_kinbara/3-17/3-17.html, 106_kinbara/3-17/todolist.js
=> 金原/3-17/classList

66_koizumi_saori/level3-5/index3_5.html
=> Level3-5 小泉沙織　JS演算

66_koizumi_saori/level3-7/index3_7.html
お疲れ様です！
課題提出いたします。何卒宜しくお願いいたします！
=> Level3-7 小泉沙織　条件分岐

66_koizumi_saori/level3-8/index3_8.html
おはようございます！
課題提出いたします、何卒宜しくお願いいたします！
=> Ｌevel3-8 小泉沙織　関数定義

117_sudou_taisei/index_3_8.html
お疲れ様です！
level3-8 課題提出いたします。
ご確認のほど、よろしくお願いいたします。
=> level3-8 須藤大晴 関数定義

66_koizumi_saori/level3-5/index3_5.html, 66_koizumi_saori/level3-7/index3_7.html, 66_koizumi_saori/level3-8/index3_8.html, 66_koizumi_saori/level3-9/index3_9.html
お疲れ様です！
課題提出いたします。よろしくお願いいたします。
=> Level3-9 小泉沙織　配列計算

66_koizumi_saori/level3-10/index3_10.html, 66_koizumi_saori/level3-9/index3_9.html
お疲れ様です！
課題提出いたします。
よろしくお願いいたします！
=> Level3-10　小泉沙織　要素の変更

66_koizumi_saori/level3-10/index3_10.html, 66_koizumi_saori/level3-11/index3_11.html, 66_koizumi_saori/level3-9/index3_9.html
お疲れ様です！
課題提出いたします。
よろしくお願いいたします！
=> Level3-11　小泉沙織　構文の使い方

66_koizumi_saori/level3-12/index3_12.html
お疲れ様です。
課題提出いたします。
よろしくお願いいたします！
=> Level3-12　小泉沙織　配列置き換え

117_sudou_taisei/index_3_9.html
お疲れ様です！
level3-9 課題提出致します。
ご確認の程、よろしくお願いいたします。
=> level3-9 須藤大晴 配列計算

66_koizumi_saori/level3-13/index3_13.html
お疲れ様です！
課題提出いたします。
何卒宜しくお願い致します。
=> Level3-13　小泉沙織　Math.randomサイコロ

90_takagishi_miwa/4-3/Coffee.php, 90_takagishi_miwa/4-3/Dripper.php, 90_takagishi_miwa/4-3/IDrip.php, 90_takagishi_miwa/4-3/Matcha.php, 90_takagishi_miwa/4-3/Tea.php, 90_takagishi_miwa/4-3/index.php
=> ｐ4－3/髙岸/外部ファイルを読み込む　課題提出

117_sudou_taisei/index_3_11.html
お疲れ様です！
Level3-11構文の使い方、課題提出致します！
ご確認の程よろしくお願いいたします。
=> Level3-11 須藤大晴 構文の使い方

92_seino_daisuke/Patient.php, 92_seino_daisuke/Person.php, 92_seino_daisuke/indexP4-1.php, 92_seino_daisuke/php-7answer.txt
お疲れ様でございます。
P4-1,オブジェクト指向1課題提出させて頂きます
お手隙きの際確認よろしくお願いいたします。
=> 情野_p4_1_課題提出

117_sudou_taisei/index_3_12.html
お疲れ様です！
Level3-12課題提出いたします！
ご確認の程、宜しくお願いいたします。
=> Level3-12 須藤大晴 オブジェクトの作り方

79_sonoyama_ryouga/level7-2/level7_3_table_study.sql
2 テーブルを作成してみよう　が完了したため、確認をお願い致します。
=> 園山　2 テーブルを作成してみよう　の提出

92_seino_daisuke/P4_3/Coffee.php, 92_seino_daisuke/P4_3/Dripper.php, 92_seino_daisuke/P4_3/IDrip.php, 92_seino_daisuke/P4_3/Matcha.php, 92_seino_daisuke/P4_3/Tea.php, 92_seino_daisuke/P4_3/index.php
お疲れ様でございます。
P4_3課題を提出させて頂きます
お手隙きの際確認よろしくお願いいたします。
=> 情野 P4_3課題提出 外部ファイルを読み込む

117_sudou_taisei/3_14/index_3_14.html, 117_sudou_taisei/3_14/js/script.js, 117_sudou_taisei/index_3_14.html
Level3-14，課題仮提出いたします
ご確認の程、よろしくお願いいたします。
=> level3-14　須藤大晴　いろんなメソッド

106_kinbara/3-20/3-20.html
=> 金原/3-20/canvasAPIを利用しよう！（1）

106_kinbara/3-20/3-20.html, 106_kinbara/3-21/3-21.html
=> 金原/3-21/Canvas APIを利用しよう！(2)

106_kinbara/3-20/3-20.html, 106_kinbara/3-21/3-21.html, 106_kinbara/3-23/index.html, 106_kinbara/3-23/js/time.js, 106_kinbara/3-23/style.css
=> 金原/3-23/JavaScript総合課題

106_kinbara/6-1/index.php
=> 金原/6-1/PHP導入

90_takagishi_miwa/6/level7_3_table_study.sql
お疲れ様です。
P-6. テーブルを作成してみようの課題を提出いたします。
ご確認よろしくお願いいいたします。
=> P-6/髙岸/テーブルを作成してみよう　課題提出

55_furukawa_maya/index_3_8/index_3_8.html
お疲れ様です！
L3-8課題を提出させていただきます。
ご確認お願いします
=> L3-8課題提出 古川真椰　JavaScript課題提出

55_furukawa_maya/index_3_10/index_3_10.html
お疲れ様です！
L3-10の課題を提出させていただきます。
課題について出力結果の続きも表示させるべきか分からなかったので、
一旦表示させられるように調べながらコードを作成してみました。
ご確認よろしくお願いします
=> L3-10 古川真椰 JavaScript課題提出

55_furukawa_maya/index_3_11/index_3_11.html
お疲れ様です
L3-11の課題を提出させていただきます！
ご確認お願いします！
=> L3-11　古川真椰　JavaScript課題提出

89_toyoshima_erina/HTML/index_2_1.html, 89_toyoshima_erina/HTML/index_2_2.html
お疲れ様です。
HTML1 ,2,3課題提出させていただきます。
2と3はまとめてindex2_2で作成いたしました。
=> 豊島　mtml1 indexファイル提出

55_furukawa_maya/index_3_12/index_3_12.html
お疲れ様です。
L3-12の課題を提出させていただきます！
ご確認よろしくお願いします。
=> L3-12 古川真椰 JavaScript課題提出

89_toyoshima_erina/index_2_4.html
=> 豊島　html４　課題

106_kinbara/6-2/6-2.php
=> 金原/6-2/phpの基本を書いていこう

89_toyoshima_erina/HTML/index_2_10.html, 89_toyoshima_erina/HTML/index_2_8.html, 89_toyoshima_erina/HTML/index_2_9.html
お疲れ様です。
html課題8,9,10提出させて頂きます。
=> 豊島　html8,9,10

89_toyoshima_erina/CSS/css2_14.css, 89_toyoshima_erina/CSS/index_2_11.html, 89_toyoshima_erina/CSS/index_2_12.html, 89_toyoshima_erina/CSS/index_2_14.html, 89_toyoshima_erina/CSS/index_2_15.html
お疲れ様です。
課題2-11〜2-15までの課題提出させて頂きます。
index_2_11ファイルのみ少し見落としていた箇所あったので修正して再度pushいたしました。
=> 豊島　css2-11~15課題ファイル

115_kimura_ruuna/index_1.php
お疲れ様です。
G-3 Githubを使った作業の課題を提出いたします。
=> G-3 Githubを使った作業　木村瑠夏

55_furukawa_maya/index_3_14/index_3_14.html
お疲れ様です！
L3-14の課題を提出させていただきます。
ご確認よろしくお願いします。
=> L3-14　古川真椰　JavaScript課題提出

89_toyoshima_erina/CSS/index_2_16.html, 89_toyoshima_erina/CSS/index_2_17.html, 89_toyoshima_erina/CSS/index_2_18.html
おつかれさまです。
CSS課題１６〜１８提出させて頂きます。
=> 豊島　CSS 16-18課題

89_toyoshima_erina/CSS/index_2_19.html, 89_toyoshima_erina/CSS/index_2_20.html, 89_toyoshima_erina/CSS/index_2_21.html, 89_toyoshima_erina/CSS/index_2_22.html
お疲れ様です。
CSS課題2-19~22提出させて頂きます。
=> 豊島　19-22 課題

08_kubota_nana/index._3_7.html
お疲れ様です。
L3-7課題提出いたします。
ご確認お願いいたします。
=> L3-7課題提出　久保田奈那　Level3-7 条件分岐

118_tezuka_saki/Laravel/Sample/app/Http/Controllers/ApiSample.php, 118_tezuka_saki/Laravel/Sample/routes/api.php
=> 手塚 L8-1 API

92_seino_daisuke/level7_3_table_study.sql
お疲れ様でございます。
p6課題提出させて頂きます
お手隙きの際確認よろしくお願いいたします。
=> p6_情野_MySQLテーブル作成_課題提出

90_takagishi_miwa/2-1/index_2_1.html
お疲れ様です。
1.HTMLを作成しよう！の課題を提出致します。
ご確認よろしくお願いします。
=>  2-1/髙岸/HTMLを作成しよう！

13_fukunaga_taisuke/level3-4/Level3-4.html
=> L3_4 福永泰佑 JavaScriptを学ぼう課題提出

90_takagishi_miwa/2-3/index_2_3.html
=> 2-3/髙岸/ タグと要素

90_takagishi_miwa/2-4/index_2_4.html
お疲れ様です。
4 セクションの課題を提出いたします。
ご確認よろしくお願いします。
=> 2-4/髙岸/ セクション

79_sonoyama_ryouga/Laravel/sample/app/Console/Commands/BirthdayMail.php, 79_sonoyama_ryouga/Laravel/sample/app/Http/Controllers/ApiTestController.php, 79_sonoyama_ryouga/Laravel/sample/app/Jobs/sendmail.php, 79_sonoyama_ryouga/Laravel/sample/app/Mail/SampleMail.php, 79_sonoyama_ryouga/Laravel/sample/database/migrations/2023_07_21_145357_create_jobs_table.php, 79_sonoyama_ryouga/Laravel/sample/database/migrations/2023_07_21_164301_add_user_is_table.php, 79_sonoyama_ryouga/Laravel/sample/routes/web.php
Level8-2　非同期＆バッチ処理　が完了したため、確認をお願い致します。
=> 園山　Level8-2　非同期＆バッチ処理　の提出

115_kimura_ruuna/level7_3_table_study.sql
お疲れ様です！
P-6. テーブルを作成してみよう　の課題を提出いたします。
ご確認お願い致します。
=> p-6　木村瑠夏　課題提出

13_fukunaga_taisuke/level3-5/L3-5.html
=> L3-5 福永泰佑　課題提出 

55_furukawa_maya/index_3_17/index_3_17.html
お疲れ様です！
L3-30の課題が出来ましたので提出させていただきます。
=> L3-17 古川真椰　JavaScript課題提出

120_yoshizawa_izuki/index_1.php
お疲れ様です。
p2-1PHPの基本を書いていこうを提出させていただきます。
ご確認お願いします！
=> p2-1 吉澤出稀　PHPの基本を書いていこう提出

55_furukawa_maya/index_3_18/index_3_18.html
お疲れ様です！
L3-18の課題を提出させていただきます。
ご確認よろしくお願いします！
=> L3-18　古川真椰　JavaScript課題提出

55_furukawa_maya/index_3_20/index_3_20.html
お疲れ様です！
L3-20の課題を提出させていただきます。
ご確認よろしくお願いします！
=> L3-20 古川真椰　JavaScript課題提出

89_toyoshima_erina/js/index3_4.html, 89_toyoshima_erina/js/index3_5.html, 89_toyoshima_erina/js/index3_7.html
=> 豊島　3-4~7課題

08_kubota_nana/index._3_12.html
お疲れ様です。
課題提出になります。ご確認お願いいたします。
=> Level3-12 オブジェクトの作り方　久保田奈那

90_takagishi_miwa/2-6/index_2_6.html, 90_takagishi_miwa/2-7/index_2_7.html
お疲れ様です。
7　フォーム部品についての課題を提出いたします。
ご確認よろしくお願いします。
=> 2-7/髙岸/ フォーム部品について

90_takagishi_miwa/2-6/index_2_6.html
お疲れ様です。
6 リスト, テーブルの表現の課題を提出いたします。
ご確認よろしくお願いします。
=> 2-6/髙岸/ リスト, テーブルの表現

90_takagishi_miwa/2-7/index_2_7.html, 90_takagishi_miwa/2-8/index_2_8.html
お疲れ様です。
8 入力部品を使うの課題を提出いたします。
ご確認よろしくお願いします。
=> 2-8/髙岸/ 入力部品を使う

90_takagishi_miwa/2-10/index_2_10.html
お疲れ様です！
10 総合HTML課題の課題を提出いたします！
ご確認よろしくお願いします！
=> 2-10/高岸/ 総合HTML課題

08_kubota_nana/index._3_13.html
お疲れ様です。
課題提出になります。
ご確認お願いいたします。
=> Level3-13配列とオブジェクトの組み合わせ 久保田奈那

90_takagishi_miwa/2-11/css/style.css, 90_takagishi_miwa/2-11/index.html
お疲れ様です。
Level2-11 CSS基礎課題を提出いたします。
=> Level2-11/高岸/ CSS基礎

08_kubota_nana/index._3_14.html
お疲れ様です。
課題提出になります。ご確認お願いいたします。
=> Level3-14 いろんなメソッド　久保田奈那

90_takagishi_miwa/2-11/css/style.css, 90_takagishi_miwa/2-11/index.html, 90_takagishi_miwa/2-12/index_2_12.html
お疲れ様です。
Level2-12 CSS スタイルの継承の課題を提出いたします。
ご確認よろしくお願いします。
=> Level2-12/高岸/ CSS スタイルの継承　課題提出

89_toyoshima_erina/js/index3_11.html, 89_toyoshima_erina/js/index3_12.html, 89_toyoshima_erina/js/index3_13.html
お疲れ様です。
js課題3-11~3-13課題提出させて頂きます。
=> 豊島　js11-13　提出

90_takagishi_miwa/2-12/Untitled-1.html, 90_takagishi_miwa/2-12/css/style.css, 90_takagishi_miwa/2-14/index_2_14.html, 90_takagishi_miwa/2-15/index_2_15.html, 90_takagishi_miwa/2-8/index_2_9.html
お疲れ様です。
「Level2-15 初期値について、ボックスモデルと指定プロパティ」の課題を提出いたします。
ご確認よろしくお願いします。
=> Level2-15/高岸/ 初期値について、ボックスモデルと指定プロパティ　課題提出

90_takagishi_miwa/2-12/Untitled-1.html, 90_takagishi_miwa/2-14/index_2_14.html
お疲れ様です。
Level2-14 スタイルを設定しようの課題を提出いたしました。
ご確認よろしくお願いします。
=> Level2-14 /高岸/スタイルを設定しよう

90_takagishi_miwa/2-16/index_2_16.htm
お疲れ様です。
「Level2-16 要素を絶対配置する」の課題を提出いたします。
ご確認よろしくお願いします。
=> Level2-16/高岸/要素を絶対配置する

加藤瑞希/index1.php
お疲れ様です。
gitのテストなので、一旦加藤さんのを使っています。
=> ｐ1-1 ozeki_test

79_sonoyama_ryouga/level7_9/shellscript.sh
P1-2. コマンドラインにふれる　が完了したため、確認をお願い致します。
=> 園山　P1-2. コマンドラインにふれる　の提出

08_kubota_nana/index._3_15.html
お疲れ様です。
課題提出になります。ご確認お願いいたします。
=> L3-15ソッドやクラスを使う 久保田奈那

90_takagishi_miwa/2-13/index_2_14.html, 90_takagishi_miwa/2-17/index_2_17.html, 90_takagishi_miwa/2-18/index_2_18.html
お疲れ様です。
「Level2-18 擬似要素、擬似クラス」の課題を提出いたします。
ご確認よろしくお願いします。
=> Level2-18/高岸/ 擬似要素、擬似クラス　

90_takagishi_miwa/2-13/index_2_14.html, 90_takagishi_miwa/2-17/index_2_17.html
お疲れ様です。
Level2-17 属性セレクターを使うの課題を提出いたします。
ご確認よろしくお願いします。
=> Level2-17/高岸/ 属性セレクターを使う

90_takagishi_miwa/2-19/index_2_19.html
お疲れ様です。
「Level2-19 フレックスボックス」の課題を提出いたします。
ご確認よろしくお願いします。
=> Level2-19/高岸/ フレックスボックス　

119_yakagomi_yuuya/index_2.1.php, 119_yakagomi_yuuya/index_3.php, 119_yakagomi_yuuya/index_5.php, 119_yakagomi_yuuya/index_6.php
お疲れ様です。
G-3の課題を提出させていただきます。
ご確認よろしくお願いします。
=> G-3 中込裕也　GitHubを使った作業

13_fukunaga_taisuke/level3-7/3-7.html
=> L3-7福永泰佑　課題提出

90_takagishi_miwa/2-19/index_2_19.html, 90_takagishi_miwa/2-20/index_2_20.html
お疲れ様です。
「Level2-20 画像の配置」の課題を提出いたします。
ご確認よろしくお願いします。
=> Level2-20/高岸/ 画像の配置

90_takagishi_miwa/2-21/index_2_21.html
お疲れ様です！
「Level2-21 アニメーションを使う」の課題を途中経過ですが、提出いたします。
課題についての質問です。
タブの切り替えで、表示されるコンテンツも変わるようにしたいのですが、
非表示にはできても、クリックしたときの表示ができません。
他のサイトも調べながら試していますが、どこに誤りがあるかわからないのでご教示ください。
=> Level2-21/高岸/ アニメーションを使う

90_takagishi_miwa/2-21/index_2_21.html, 90_takagishi_miwa/2-22/index_2_22.html
お疲れ様です。
「Level2-22 レスポンシブWebデザイン」の課題を提出いたします。
ご確認よろしくお願いします。
=> Level2-22/高岸/ レスポンシブWebデザイン

55_furukawa_maya/index_3_21/index_3_21.html, 55_furukawa_maya/index_3_23/index_3_23.html, 55_furukawa_maya/index_3_23/style.css, 55_furukawa_maya/index_3_23/time.js
=> L3-23　古川真椰　JavaScript課題提出

120_yoshizawa_izuki/p4-2.オブジェクト指向を覚える-2/p4-2.オブジェクト指向を覚える-2/Coffee.php, 120_yoshizawa_izuki/p4-2.オブジェクト指向を覚える-2/p4-2.オブジェクト指向を覚える-2/Dripper.php, 120_yoshizawa_izuki/p4-2.オブジェクト指向を覚える-2/p4-2.オブジェクト指向を覚える-2/IDrip.php, 120_yoshizawa_izuki/p4-2.オブジェクト指向を覚える-2/p4-2.オブジェクト指向を覚える-2/Tea.php, 120_yoshizawa_izuki/p4-2.オブジェクト指向を覚える-2/p4-2.オブジェクト指向を覚える-2/index.php
お疲れ様です。
p4-2オブジェクト指向を覚える-2の課題を提出いたします。
ご確認お願い致します！
=> p4-2　吉澤出稀　課題提出

90_takagishi_miwa/2-23/index_2_23.html
お疲れ様です。
「Level2-23 グリッドの設定」の課題を提出いたします。
ご確認よろしくお願いします。
=> Level2-23/高岸/ グリッドの設定

13_fukunaga_taisuke/level3-8/L3-8.html
お疲れ様です。
課題提出いたします。
ご確認よろしくお願いします。
=> L3-8 福永泰佑　課題提出

13_fukunaga_taisuke/level3-9/3-9.html
=> L3-9 福永泰佑　課題提出

124_ozeki_hiroka/P4-1-2Patient.php, 124_ozeki_hiroka/P4-1-2Person.php, 124_ozeki_hiroka/P4-1-2index.php
お疲れ様です。
P4-1の１と２の課題を提出いたします。
ご確認お願い致します。
=> P4-1 尾関広華　課題提出

90_takagishi_miwa/2-21/Untitled-1.html, 90_takagishi_miwa/2-21/index_2_21.html, 90_takagishi_miwa/2-24/index_2_24.html
お疲れ様です。
「Level2-24 CSS変数の宣言」の課題を提出いたしました！
ご確認よろしくお願いします！
=> Level2-24/高岸/ CSS変数の宣言

119_yakagomi_yuuya/Patient.php, 119_yakagomi_yuuya/Person.php, 119_yakagomi_yuuya/index.php, 119_yakagomi_yuuya/php-7-answer.txt
お疲れ様です。P4-1の課題を提出させていただきます
ご確認の程よろしくお願いします。
=> P4-1 中込裕也　オブジェクト指向を覚える

120_yoshizawa_izuki/p4-3.外部ファイルを読み込む/Coffee.php, 120_yoshizawa_izuki/p4-3.外部ファイルを読み込む/Dripper.php, 120_yoshizawa_izuki/p4-3.外部ファイルを読み込む/IDrip.php, 120_yoshizawa_izuki/p4-3.外部ファイルを読み込む/Matcha.php, 120_yoshizawa_izuki/p4-3.外部ファイルを読み込む/Tea.php, 120_yoshizawa_izuki/p4-3.外部ファイルを読み込む/index.php
=> p4-3.外部ファイルを読み込む　課題提出

08_kubota_nana/index._3_16.html
お疲れ様です。
課題提出になります。ご確認よろしくお願いいたします。
=> L3-16課題提出 DOM(Document Object Model)

13_fukunaga_taisuke/level3-10/L3-10.html, 13_fukunaga_taisuke/level3-11/3-11.html
=> L3-11 福永泰佑　課題提出

13_fukunaga_taisuke/level3-10/L3-10.html
=> L3-10 福永泰佑　課題提出

55_furukawa_maya/p1-1/index.php
=> P1-1　古川真椰　PHP課題提出

119_yakagomi_yuuya/P4-2.オブジェクト指向を覚える２/Coffee.php, 119_yakagomi_yuuya/P4-2.オブジェクト指向を覚える２/Dripper.php, 119_yakagomi_yuuya/P4-2.オブジェクト指向を覚える２/IDrip.php, 119_yakagomi_yuuya/P4-2.オブジェクト指向を覚える２/Tea.php, 119_yakagomi_yuuya/P4-2.オブジェクト指向を覚える２/index.php
お疲れ様です。
P4-2　の課題を提出させていただきます。
ご確認の程よろしくお願いします。
=> P4-2 中込裕也　課題提出

55_furukawa_maya/L6-3/index.php, 55_furukawa_maya/L6-3/member.csv
お疲れ様です。
課題６−３を提出させて頂きます！
ご確認お願いします。
=> L6-3　古川真椰　PHP課題提出

119_yakagomi_yuuya/P4-3 外部ファイルを読み込む/Coffee.php, 119_yakagomi_yuuya/P4-3 外部ファイルを読み込む/Dripper.php, 119_yakagomi_yuuya/P4-3 外部ファイルを読み込む/IDrip.php, 119_yakagomi_yuuya/P4-3 外部ファイルを読み込む/Matcha.php, 119_yakagomi_yuuya/P4-3 外部ファイルを読み込む/Tea.php, 119_yakagomi_yuuya/P4-3 外部ファイルを読み込む/index.php
お疲れ様です。夜分遅くに申し訳ございません。
P4-3外部ファイルを読み込むの課題を提出させていただきます！
ご確認の程よろしくお願いします！
=> P4-3 中込裕也　課題提出

120_yoshizawa_izuki/p-6.テーブルを作成してみよ/level7_3_table_study.sql
お疲れ様です。
p－6の課題を提出いたします。
ご確認お願い致します！
=> p-6　吉澤出稀　課題提出

120_yoshizawa_izuki/p-7.レコードを挿入しよう/profiles_place.txt, 120_yoshizawa_izuki/p-7.レコードを挿入しよう/users_profiles.txt
お疲れ様です。
p-7.レコードを挿入してみようの課題提出をいたします。
ご確認お願い致します。
=> p-7 吉澤出稀　課題提出

112_iwakara_koutarou/php-7-answer.txt
お疲れ様です！
P4-1-1　課題を提出させていただきます。
ご確認よろしくお願いしたします！
=> P4-1　岩川浩太朗　オブジェクト指向を覚える課題1提出

112_iwakara_koutarou/Coffee.php, 112_iwakara_koutarou/Dripper.php, 112_iwakara_koutarou/IDrip.php, 112_iwakara_koutarou/Tea.php, 112_iwakara_koutarou/index.php
お疲れ様です！
P4-2 課題完了しましたので確認お願いいたします。
=> P4-2 岩川浩太朗 オブジェクト指向を覚える2課題提出

08_kubota_nana/index._3_18.html
=> L3-18 フォームの操作を理解しよう！久保田奈那

08_kubota_nana/index._3_20.html, 08_kubota_nana/index._3_21.html
お疲れ様です。
2つの課題提出になります。ご確認お願いいたします
=> L3-20/21課題提出　久保田奈那　CanvasAPIを利用しよう!(1)（2）

08_kubota_nana/index._3_22.html
=> l3-22 高解像度ディスプレイの対応 久保田奈那

13_fukunaga_taisuke/level3-12/3-12.html, 13_fukunaga_taisuke/level3-13/3-13.html
=> L3-13 福永泰佑　課題提出

13_fukunaga_taisuke/level3-12/3-12.html
=> L3-12 　福永泰佑　課題提出

13_fukunaga_taisuke/level3-12/3-12.html, 13_fukunaga_taisuke/level3-13/3-13.html, 13_fukunaga_taisuke/level3-14.15/3-15.html, 13_fukunaga_taisuke/level3-14.15/L3-14.html
=> L3-14.15 福永泰佑　課題提出

124_ozeki_hiroka/P5/P-5.txt
お疲れ様です。Pー５の課題を提出させていただきました。
ご確認をお願い致します。
=> P5 SQL課題提出

13_fukunaga_taisuke/level3-16/L3-16.html
お疲れ様です。
課題提出致します。
ご確認よろしくおねがいします。
=> L3-16 福永泰佑　課題提出

01_kato/Sample/app/Http/Controllers/TodoListController.php, 01_kato/Sample/app/Models/TodoList.php, 01_kato/Sample/database/migrations/2023_11_12_235228_create_todo_lists_table.php, 01_kato/Sample/database/seeders/DatabaseSeeder.php, 01_kato/Sample/database/seeders/TodoListSeeder.php, 01_kato/Sample/resources/views/todo_list/index.blade.php, 01_kato/Sample/routes/web.php
=> P-9Laravelフレームワーク（実装編）加藤瑞希

13_fukunaga_taisuke/level3-17/L3-17.html
お疲れ様です。
課題提出しました。
ご確認よろしくお願いします。
=> L3-17 福永泰佑　課題提出

13_fukunaga_taisuke/level3-18/L3-18.html
=> 福永/3-18/フォームの操作を理解しよう

140_wakahara_momoka/index_1.php
=> L3-2 若原百花　Githubを使った作業提出課題

13_fukunaga_taisuke/level3-20/L3-20.html
お疲れ様です。
課題提出致します。
ご確認よろしくお願いします。
=> 福永/3-20/Canvas APIを利用しよう！(1)

152_tanabe_takatoshi/Level6-3/index.php, 152_tanabe_takatoshi/Level6-3/member.csv
お疲れ様です。
Level6-3課題提出させせて頂きます。
ご確認お願いします
=> Level6-3 田邊威斗　PHP 課題提出

152_tanabe_takatoshi/Level6-4/index.php
お疲れ様です。
Level6-4の課題提出をさせて頂きます。
ご確認よろしくお願いします。
=> Level6-4 田邊　PHP 課題提出

08_kubota_nana/Level6-2/index.php
お疲れ様です。
L6-2課題提出になります。
ご確認お願い致します。
=> p-2 phpの基本を書いていこう! 久保田奈那

13_fukunaga_taisuke/level3-21/3-21.html
お疲れ様です。
課題提出します。
ご確認よろしくお願いします。
=> 福永/3-21/Canvas APIを利用しよう！(2)

152_tanabe_takatoshi/P4-2/Coffee.php, 152_tanabe_takatoshi/P4-2/Dripper.php, 152_tanabe_takatoshi/P4-2/IDrip.php, 152_tanabe_takatoshi/P4-2/Tea.php, 152_tanabe_takatoshi/P4-2/index.php
お疲れさまです。
P4-2の課題の提出をいたしますので
確認の方よろしくお願いします。
=> P4-2　田邊　PHP演習コース課題提出

08_kubota_nana/L6-3/index.php, 08_kubota_nana/L6-3/member.csv
お疲れ様です。
L6-3課題提出になります。
ご確認お願い致します。
=> P-3. phpの演習をしよう!　久保田奈那

90_takagishi_miwa/3-7/3-7 課題.html
お疲れ様です！
Level3-7 条件分岐の課題を提出します！
ご確認よろしくお願いします！
=> Level3-7/高岸/ 条件分岐

90_takagishi_miwa/3-6/Untitled-1.html, 90_takagishi_miwa/3-6/Untitled-1.js, 90_takagishi_miwa/3-8/3-8課題.html, 90_takagishi_miwa/3-8/JavaScript.html
お疲れ様です！
Level3-8 関数定義の課題を提出致します！
ご確認よろしくお願いします！
=> Level3-8/高岸/ 関数定義

90_takagishi_miwa/3-9/3-9.html, 90_takagishi_miwa/3-9/3-9課題.html
お疲れ様です！
Level3-9 配列計算の課題を提出致します！
ご確認よろしくお願いします！
=> Level3-9/高岸/ 配列計算

143_yoshida_narumi/techup_php_8/Coffee.php, 143_yoshida_narumi/techup_php_8/Dripper.php, 143_yoshida_narumi/techup_php_8/IDrip.php, 143_yoshida_narumi/techup_php_8/Tea.php, 143_yoshida_narumi/techup_php_8/index.php
=> L3-2 吉田成海　P4-2課題提出

90_takagishi_miwa/3-11/L3-11 課題.html, 90_takagishi_miwa/3-11/L3-11.html
お疲れ様です！
Level3-11　構文の使い方の課題を提出いたします！
ご確認よろしくお願いします！
=> Level3-11/高岸/構文の使い方

01_kato/Sample/app/Http/Controllers/ApiSample.php, 01_kato/Sample/app/Http/Controllers/TaskController.php, 01_kato/Sample/routes/api.php
@fujimoto-mio 
おつかれさまです！
ご提出が遅くなり申し訳ございません。
APIの課題を提出しますので、ご確認お願いいたします🙇‍♀️
=> API課題提出/加藤瑞希

13_fukunaga_taisuke/level3-22/3-22.html
お疲れ様です。
課題提出致します。
ご確認よろしくお願いします。
=> 福永/3-22/高解像度ディスプレイの対応

106_kinbara/7-6/sample/app/Http/Controllers/ApiSample.php, 106_kinbara/7-6/sample/app/Http/Controllers/TaskController.php, 106_kinbara/7-6/sample/routes/api.php
課題完了いたしました！
ご確認のほどよろしくお願いいたします！
=> 金原/8-1課題提出

126_sutou_kai/P-5. MySQL接続しよう！.txt
=> P-5　主藤魁　MySQL接続しよう！　課題提出

126_sutou_kai/level7_3_table_study.sql
お疲れ様です。
P-6の課題提出です。
ご確認よろしくお願いします。
=> P-6 主藤魁 テーブルを作成してみよう！

13_fukunaga_taisuke/level3-23/index.html, 13_fukunaga_taisuke/level3-23/style.css, 13_fukunaga_taisuke/level3-23/time.js
お疲れ様です。
課題提出致します。
ご確認よろしくお願いします。
=> 福永/3-23/Javascript総合課題

90_takagishi_miwa/3-15/L3-15 課題①.html, 90_takagishi_miwa/3-15/L3-15 課題②.html, 90_takagishi_miwa/3-15/L3-15課題.html
お疲れ様です！
Level3-15 メソッドやクラスを使うの課題を提出いたします！
ご確認よろしくお願いします！
=> Level3-15/高岸/ メソッドやクラスを使う

152_tanabe_takatoshi/HTML/HTML作成/index_2_1.html
お疲れ様です。
「HTMLを作成しよう」の課題を提出致します。
ご確認を宜しくお願いします。
=> HTMLを作成しよう 田邊　課題提出

152_tanabe_takatoshi/HTML/マークアップ/index_2_2.html
お疲れ様です。
マークアップの課題を提出いたします。
ご確認宜しくお願いします。
=> マークアップ　田邊　課題提出

127_shijyou_ryouhei/techup_php_8/Coffee.php, 127_shijyou_ryouhei/techup_php_8/Dripper.php, 127_shijyou_ryouhei/techup_php_8/IDrip.php, 127_shijyou_ryouhei/techup_php_8/Tea.php, 127_shijyou_ryouhei/techup_php_8/index.php
P4-2の課題を提出致します。
ご確認のほどよろしくお願いいたします。
=> P4-2課題提出　四條諒平

152_tanabe_takatoshi/HTML/HTML総合課題/index_2_10.html, 152_tanabe_takatoshi/HTML/divとspan/index_2_5.html, 152_tanabe_takatoshi/HTML/formタグ/index_2_9.html, 152_tanabe_takatoshi/HTML/セクション/index_2_4.html, 152_tanabe_takatoshi/HTML/タグ・要素/index_2_3.html, 152_tanabe_takatoshi/HTML/フォーム部品/index2_7.html, 152_tanabe_takatoshi/HTML/リスト・テーブル/index_2_6.html, 152_tanabe_takatoshi/HTML/入力部品/index_2_8.html
お疲れ様です。
残りのHTML課題をまとめて提出いたします。
ご確認宜しくお願いします。
=> HTML課題　田邊　提出

152_tanabe_takatoshi/JS/JS を学ぼう/index_3_4.html
お疲れ様です。
「JavaScriptを学ぼう」の課題提出をいたします。
ご確認宜しくお願いします。
=> JavaScriptを学ぼう 田邊　課題提出

152_tanabe_takatoshi/JS/JS演算_2/index_3_5.html
お疲れ様です。
JavaScript演算の課題提出をいたします。
ご確認宜しくお願いします。
=> JS演算　田邊　課題提出

152_tanabe_takatoshi/JS/JS_3条件分岐/index-3_7.html
お疲れ様です。
条件分岐の課題を提出を致しましたのでご確認をお願いします。
=> 条件分岐　田邊　課題提出

117_fukase_takumi/Coffee.php, 117_fukase_takumi/Dripper.php, 117_fukase_takumi/IDrip.php, 117_fukase_takumi/Tea.php, 117_fukase_takumi/index.php
お疲れ様です。
ｐ4－2の課題になります。ご確認をお願い致します。
=> ｐ4－2課題提出/深瀬巧

180_kuwahara_yuuhi/Patient.php, 180_kuwahara_yuuhi/Person.php, 180_kuwahara_yuuhi/index.php, 180_kuwahara_yuuhi/php-7-answer.txt
お疲れ様です。
P4-1の課題１と２を提出させていただきます。
ご確認宜しくお願いいたします。
=> P4-1　桑原雄飛　オブジェクト指向を覚える-1

180_kuwahara_yuuhi/p4-3/Coffee.php, 180_kuwahara_yuuhi/p4-3/Dripper.php, 180_kuwahara_yuuhi/p4-3/IDrip.php, 180_kuwahara_yuuhi/p4-3/Matcha.php, 180_kuwahara_yuuhi/p4-3/Tea.php, 180_kuwahara_yuuhi/p4-3/index.php
=> P4-3 桑原雄飛 外部ファイルを読み込む

178_naganuma_naoki/php-7-answer.txt, 178_naganuma_naoki/techup_php_8/Coffee.php, 178_naganuma_naoki/techup_php_8/Dripper.php, 178_naganuma_naoki/techup_php_8/IDrip.php, 178_naganuma_naoki/techup_php_8/Tea.php, 178_naganuma_naoki/techup_php_8/index.php
p4_2の課題を提出します
お手隙の際にご確認お願いします。
=> 長沼直樹　 p4＿2　課題提出

180_kuwahara_yuuhi/p-5/user.txt
=> P-5 桑原雄飛 MySQL接続しよう！

180_kuwahara_yuuhi/p-6/level7_3_table_study.sql
お疲れ様です。
L3-4 P-6 テーブルを作成してみよう の課題を提出させていただきます。
=> L3-4 桑原雄飛 P-6 テーブルを作成してみよう

178_naganuma_naoki/techup_php_8/Matcha.php, 178_naganuma_naoki/techup_php_8/index.php
=> naganuma_naoki p4 3　課題を提出

129_fukahori_chikage/index_1.php
お疲れ様です
G-3課題を提出させていただきます
ご確認よろしくお願いします
=> G-3 深堀尋景 GitHub課題提出

178_naganuma_naoki/index_2_1.html
=> 課題提出＿長沼直樹＿L2＿1

194_yamashita_haruka/p4-3/Coffee.php, 194_yamashita_haruka/p4-3/Dripper.php, 194_yamashita_haruka/p4-3/IDrip.php, 194_yamashita_haruka/p4-3/Matcha.php, 194_yamashita_haruka/p4-3/Tea.php, 194_yamashita_haruka/p4-3/index.php
=> p4-3山下遥　PHP演習コース課題提出

194_yamashita_haruka/level7_3_table_study.sql
=> p6　山下遥　PHP演習コース課題提出

188_takahashi_mei/Person.php, 188_takahashi_mei/index.php, 188_takahashi_mei/index_4_1.php, 188_takahashi_mei/patient.php
課題を提出いたします。
P4-1. オブジェクト指向を覚える（課題１）
ご確認お願い致します。
=> 高橋芽愛　P4-1. オブジェクト指向を覚える（課題１）

yamagishi_3_4/index_3_4.html
お疲れ様です。デザイン編（JavaScript）L3-4提出致します。
ご確認の程宜しくお願い致します。
=> L3-4　山岸一角 JavaScriptを学ぼう課題提出　

156_ootsuka_ryousuke/PHP演習4-2/Coffee.php, 156_ootsuka_ryousuke/PHP演習4-2/Dripper.php, 156_ootsuka_ryousuke/PHP演習4-2/IDrip.php, 156_ootsuka_ryousuke/PHP演習4-2/Tea.php, 156_ootsuka_ryousuke/PHP演習4-2/index.php
夜分遅くに申し訳ございません。
後ほど、ご確認よろしくおねがいします。
=> 大塚亮典　PHP演習4-2. オブジェクト指向を覚える-2 課題提出

175_hagio_yusaku/p4-2/Coffee.php, 175_hagio_yusaku/p4-2/Dripper.php, 175_hagio_yusaku/p4-2/IDrip.php, 175_hagio_yusaku/p4-2/Tea.php, 175_hagio_yusaku/p4-2/index.php
=> P4-2 萩尾勇作 オブジェクト指向を覚える－２

194_yamashita_haruka/JS課題/JS/js3-10.js, 194_yamashita_haruka/JS課題/JS/js3-11.js, 194_yamashita_haruka/JS課題/JS/js3-12.js, 194_yamashita_haruka/JS課題/JS/js3-13.js, 194_yamashita_haruka/JS課題/JS/js3-14.js, 194_yamashita_haruka/JS課題/JS/js3-15.js, 194_yamashita_haruka/JS課題/JS/js3-16.js, 194_yamashita_haruka/JS課題/JS/js3-18.js, 194_yamashita_haruka/JS課題/JS/js3-5.js, 194_yamashita_haruka/JS課題/JS/js3-6.js, 194_yamashita_haruka/JS課題/JS/js3-7.js, 194_yamashita_haruka/JS課題/JS/js3-8.js, 194_yamashita_haruka/JS課題/JS/js3-9.js, 194_yamashita_haruka/JS課題/index_3_10.html, 194_yamashita_haruka/JS課題/index_3_11.html, 194_yamashita_haruka/JS課題/index_3_12.html, 194_yamashita_haruka/JS課題/index_3_13.html, 194_yamashita_haruka/JS課題/index_3_14.html, 194_yamashita_haruka/JS課題/index_3_15.html, 194_yamashita_haruka/JS課題/index_3_16.html, 194_yamashita_haruka/JS課題/index_3_17.html, 194_yamashita_haruka/JS課題/index_3_18.html, 194_yamashita_haruka/JS課題/index_3_5.html, 194_yamashita_haruka/JS課題/index_3_6.html, 194_yamashita_haruka/JS課題/index_3_7.html, 194_yamashita_haruka/JS課題/index_3_8.html, 194_yamashita_haruka/JS課題/index_3_9.html, 194_yamashita_haruka/JS課題/todolist.js
お疲れ様です。
Level3-5から3-18の課題を提出させていただきます。
ご確認よろしくお願いします。
=> Level3-5-3-18課題提出

174_yoshimi_misaki/P4-3/Coffee.php, 174_yoshimi_misaki/P4-3/Dripper.php, 174_yoshimi_misaki/P4-3/IDrip.php, 174_yoshimi_misaki/P4-3/Matcha.php, 174_yoshimi_misaki/P4-3/Tea.php, 174_yoshimi_misaki/P4-3/index.php
お疲れ様です！
P4-3課題提出をさせていただきます。
ご確認をお願いいたします。
=> P4-3吉見美咲　オブジェクト指向課題提出

156_ootsuka_ryousuke/level7_3_table_study.sql
お疲れ様です。
"P-6. テーブルを作成してみよう"の課題であるSQLファイルを提出します。
ご確認お願いします。
=> 大塚亮典 P-6 テーブルを作成してみよう

202_nuruki_touya/index_1.php, 202_nuruki_touya/p4-1/Patient.php, 202_nuruki_touya/p4-1/Person.php, 202_nuruki_touya/p4-1/index.php, 202_nuruki_touya/p4-1/php-7-answer.txt).txt
=> 202　塗木統耶　P4-1. オブジェクト指向を覚える－１　課題提出

202_nuruki_touya/p4-2/index.php, 202_nuruki_touya/p4-2/techup_php_8/Coffee.php, 202_nuruki_touya/p4-2/techup_php_8/Dripper.php, 202_nuruki_touya/p4-2/techup_php_8/IDrip.php, 202_nuruki_touya/p4-2/techup_php_8/Tea.php, 202_nuruki_touya/p4-2/techup_php_8/index.php
=> 202_塗木統耶 P4-2の課題提出!

202_nuruki_touya/p-6/level7_3_table_study.sql
=> 202_塗木統耶　P-6　課題

159_yanagawa_harurou/P4-1 オブジェクト指向を覚える１/Patient.php, 159_yanagawa_harurou/P4-1 オブジェクト指向を覚える１/Person.php, 159_yanagawa_harurou/P4-1 オブジェクト指向を覚える１/index.php, 159_yanagawa_harurou/P4-1 オブジェクト指向を覚える１/php-7-answer.txt, 159_yanagawa_harurou/P4-2 オブジェクト指向を覚える２/index.php
=> 柳川 P4-1-2 課題提出します

159_yanagawa_harurou/P4-1 オブジェクト指向を覚える１/Patient.php, 159_yanagawa_harurou/P4-1 オブジェクト指向を覚える１/Person.php, 159_yanagawa_harurou/P4-1 オブジェクト指向を覚える１/index.php, 159_yanagawa_harurou/P4-1 オブジェクト指向を覚える１/php-7-answer.txt, 159_yanagawa_harurou/P4-2 オブジェクト指向を覚える２/Coffee.php, 159_yanagawa_harurou/P4-2 オブジェクト指向を覚える２/Dripper.php, 159_yanagawa_harurou/P4-2 オブジェクト指向を覚える２/IDrip.php, 159_yanagawa_harurou/P4-2 オブジェクト指向を覚える２/Tea.php, 159_yanagawa_harurou/P4-2 オブジェクト指向を覚える２/index.php
=> 柳川 P4-2 課題提出します　修正（不足しているファイルを追加）

159_yanagawa_harurou/P4-3 外部ファイルを読み込む/Coffee.php, 159_yanagawa_harurou/P4-3 外部ファイルを読み込む/Dripper.php, 159_yanagawa_harurou/P4-3 外部ファイルを読み込む/IDrip.php, 159_yanagawa_harurou/P4-3 外部ファイルを読み込む/Matcha.php, 159_yanagawa_harurou/P4-3 外部ファイルを読み込む/Tea.php, 159_yanagawa_harurou/P4-3 外部ファイルを読み込む/index.php
=> 柳川 P4-3 課題提出します

159_yanagawa_harurou/P4-1 オブジェクト指向を覚える１/php-7-1-answer.txt, 159_yanagawa_harurou/P4-1 オブジェクト指向を覚える１/php-7-answer.txt
=> 柳川 P4-1-1 課題提出します　修正

202_nuruki_touya/Laravel/Sample/app/Http/Controllers/TaskController.php, 202_nuruki_touya/Laravel/Sample/app/Http/Controllers/TodoListController.php, 202_nuruki_touya/Laravel/Sample/app/Models/Task.php, 202_nuruki_touya/Laravel/Sample/database/migrations/2025_01_28_204535_create_tasks_table.php, 202_nuruki_touya/Laravel/Sample/resources/views/tasks/edit.blade.php, 202_nuruki_touya/Laravel/Sample/resources/views/tasks/index.blade.php, 202_nuruki_touya/Laravel/Sample/routes/web.php
お疲れ様です。
P-10　P-10. PDOオブジェクトを使う　の課題提出致します。
コード内に自分なりの解釈を入れたコメントアウトなどもしております。
お手隙の際でご確認お願いいたします。
又、今回プッシュする際、Gitbashでは編集、追加したファイルのみステージングしコミットしました。
（手作業でファイルを全て置き換えた後、全てのファイルをステージング、コミットするとファイル量が恐らくとんでもないことになってしまうと思ったため）
こちらの方法で問題ないのでしょうか？
又、ステージングする際、add ~/ファイル名　と一つ一つコマンド入力していましたが、これらを省略する方法はありますか？
=> 202_塗木統耶　P-10課題提出します！

202_nuruki_touya/Laravel/Sample/app/Http/Controllers/ApiSample.php, 202_nuruki_touya/Laravel/Sample/routes/api.php
=> 202_塗木統耶_L8-1 課題提出

202_nuruki_touya/Laravel/Sample/app/Console/Commands/BirthdayMail.php, 202_nuruki_touya/Laravel/Sample/app/Http/Controllers/ApiSample.php, 202_nuruki_touya/Laravel/Sample/app/Jobs/sendmail.php, 202_nuruki_touya/Laravel/Sample/app/Mail/SampleMail.php, 202_nuruki_touya/Laravel/Sample/app/Models/User.php, 202_nuruki_touya/Laravel/Sample/database/migrations/2025_02_05_213119_add_user_is_table.php, 202_nuruki_touya/Laravel/Sample/routes/web.php
お疲れ様です！
L8-2 非同期＆バッチ処理　課題提出致します！
今回、MySQLのデータが破損、バックアップを取るのを忘れていたのでP-7で使用したダンプファイルから復旧しました...
今回の課題では、エラーなど紆余曲折あり提出ファイルが少し多くなっているかと思います。
ローカルでは「http://localhost:8000/dataInsertでテーブルに挿入、php artisan send:birthday-mailで送信」ができたので提出させていただきます。
もし、問題あればもう一度ファイルを見直し再提出させていただきます！
=> 202_塗木統耶　L8-2 非同期＆バッチ処理　課題提出

127_shijyou_ryouhei/testsample/app/Http/Controllers/ApiSample.php, 127_shijyou_ryouhei/testsample/app/Http/Controllers/TaskController.php, 127_shijyou_ryouhei/testsample/app/Models/Task.php, 127_shijyou_ryouhei/testsample/bootstrap/cache/config.php, 127_shijyou_ryouhei/testsample/bootstrap/cache/routes-v7.php, 127_shijyou_ryouhei/testsample/database/migrations/2024_11_19_224239_create_tasks_table.php, 127_shijyou_ryouhei/testsample/resources/views/tasks/edit.blade.php, 127_shijyou_ryouhei/testsample/resources/views/tasks/index.blade.php, 127_shijyou_ryouhei/testsample/routes/api.php, 127_shijyou_ryouhei/testsample/routes/web.php
=> Level8-1API課題提出　四條諒平

202_nuruki_touya/techUPstudy_HTML課題/index_2_2.html, 202_nuruki_touya/techUPstudy_HTML課題/index_2_5.html, 202_nuruki_touya/techUPstudy_HTML課題/index_2_6.html, 202_nuruki_touya/techUPstudy_HTML課題/index_2_7.html, 202_nuruki_touya/techUPstudy_HTML課題/index_2_8.html
お疲れ様です
HTML課題5～8　提出致します！
お手隙でご確認お願いいたします！
=> 202_塗木統耶　HTML5∼8　課題提出

202_nuruki_touya/techUPstudy_HTML課題/index_2_10.html, 202_nuruki_touya/techUPstudy_HTML課題/index_2_9.html, 202_nuruki_touya/techUPstudy_HTML課題/result.html
お疲れ様です！
HTML9~10の課題を提出致します！
お手隙の際でご確認お願いいたします！
=> 202_塗木統耶　HTML9~10課題提出

175_hagio_yusaku/.gitignore, 175_hagio_yusaku/p5/MySQL.txt
お疲れ様です！
p5の課題を提出させていただきます。
確認よろしくお願いいたします！
=> p5　萩尾勇作　MySQL接続しよう！

202_nuruki_touya/techUPstudy_HTML課題/css/style11.css, 202_nuruki_touya/techUPstudy_HTML課題/css/style12.css, 202_nuruki_touya/techUPstudy_HTML課題/css/style14.css, 202_nuruki_touya/techUPstudy_HTML課題/index_2_11.html, 202_nuruki_touya/techUPstudy_HTML課題/index_2_12.html, 202_nuruki_touya/techUPstudy_HTML課題/index_2_14.html
お疲れ様です！
HTML/CSS課題　11~14を提出致します！
お手隙の際でご確認お願いいたします！
=> 202_塗木統耶　CSS11~14課題提出

174_yoshimi_misaki/level7_3_table_study.sql
お疲れ様です！夜分にすみません。
P-6　課題提出させていただきます。
ご確認をお願いいたします。
=> 吉見美咲　P-6課題提出

202_nuruki_touya/techUPstudy_HTML課題/css/style18.css, 202_nuruki_touya/techUPstudy_HTML課題/css/style19.css, 202_nuruki_touya/techUPstudy_HTML課題/css/style20.css, 202_nuruki_touya/techUPstudy_HTML課題/css/style21.css, 202_nuruki_touya/techUPstudy_HTML課題/css/style22.css, 202_nuruki_touya/techUPstudy_HTML課題/index_2_19.html, 202_nuruki_touya/techUPstudy_HTML課題/index_2_20.html, 202_nuruki_touya/techUPstudy_HTML課題/index_2_21.html, 202_nuruki_touya/techUPstudy_HTML課題/index_2_22.html
お疲れ様です！
CSS19~22までの課題を提出致します！
お手隙の際でご確認お願いいたします！
=> 202_塗木統耶　CSS19~22課題提出

175_hagio_yusaku/p6/level7_3_table_study.sql
=> p6 萩尾勇作 テーブルを作成してみよう！

188_takahashi_mei/Laravel_samlpe/app/Http/Controllers/ApiSample.php, 188_takahashi_mei/Laravel_samlpe/routes/api.php
課題を提出します。『Level8-1 API』
ご確認お願いします！
=> 高橋芽愛　Level8-1 API

214_tsugane_saki/index_1.php, 214_tsugane_saki/index_2.php, 214_tsugane_saki/index_3.php
=> G-3　津金沙季　Gitを使った作業

202_nuruki_touya/techUPstudy_JavaScript課題/index_3_11.html, 202_nuruki_touya/techUPstudy_JavaScript課題/index_3_12.html, 202_nuruki_touya/techUPstudy_JavaScript課題/js/script_3_11.js, 202_nuruki_touya/techUPstudy_JavaScript課題/js/script_3_12.js
お疲れ様です。
JavaScript課題11~12提出致します。
お手隙でご確認お願いいたします。
=> 202_塗木統耶 JavaScript課題11~12提出

165_yamagishi/p4-2/Coffee.php, 165_yamagishi/p4-2/Dripper.php, 165_yamagishi/p4-2/IDrip.php, 165_yamagishi/p4-2/Tea.php, 165_yamagishi/p4-2/index.php
お疲れ様です。
P4-2課題提出させて頂きます。
ご確認の程宜しくお願い致します。
=> ｐ4-2　山岸一角　オブジェクト指向を覚える－２課題提出

214_tsugane_saki/P4-2/Coffee.php, 214_tsugane_saki/P4-2/Dripper.php, 214_tsugane_saki/P4-2/IDrip.php, 214_tsugane_saki/P4-2/Tea.php, 214_tsugane_saki/P4-2/index.php
=> P4-2　津金沙季　オブジェクト指向について

214_tsugane_saki/P-6/level7_3_table_study.sql
=> P-6 津金沙季 テーブルを作成

188_takahashi_mei/CSS_html/index_2_11_11.html
課題を提出します。
【Level2-11 CSS基礎】
ご確認お願いいたします。
=> 高橋芽愛　Level2-11 CSS基礎

202_nuruki_touya/techUPstudy_JavaScript課題/index_3_13.html, 202_nuruki_touya/techUPstudy_JavaScript課題/index_3_14.html, 202_nuruki_touya/techUPstudy_JavaScript課題/index_3_15.html, 202_nuruki_touya/techUPstudy_JavaScript課題/js/script_3_13.js, 202_nuruki_touya/techUPstudy_JavaScript課題/js/script_3_14.js, 202_nuruki_touya/techUPstudy_JavaScript課題/js/script_3_15.js
お疲れ様です。
JavaScript13~15課題提出致します。
お手隙でご確認お願いいたします。
=> 202_塗木統耶　JavaScript13~15課題提出

188_takahashi_mei/CSS_html/index_2_12.html
課題を提出します。＜Level2-12 CSS スタイルの継承＞
ご確認お願いいたします！
=> 高橋芽愛　Level2-12 CSS スタイルの継承

188_takahashi_mei/CSS_html/index_2_4.html
課題を提出します。【HTML/CSS_L2_4 セクション】
ご確認お願いいたします！
=> 高橋芽愛　HTML/CSS_L2_4 セクション

202_nuruki_touya/techUPstudy_JavaScript課題/index_3_16.html, 202_nuruki_touya/techUPstudy_JavaScript課題/index_3_17.html, 202_nuruki_touya/techUPstudy_JavaScript課題/js/script_3_16.js, 202_nuruki_touya/techUPstudy_JavaScript課題/js/script_3_17.js
お疲れ様です。
202_塗木統耶　JavaScript16~17課題提出致します...!
お手隙でご確認お願いいたします。
=> 202_塗木統耶　JavaScript16~17課題提出

202_nuruki_touya/techUPstudy_JavaScript課題/index_3_18.html, 202_nuruki_touya/techUPstudy_JavaScript課題/index_3_19.html, 202_nuruki_touya/techUPstudy_JavaScript課題/index_3_20.html, 202_nuruki_touya/techUPstudy_JavaScript課題/index_3_21.html, 202_nuruki_touya/techUPstudy_JavaScript課題/index_3_22.html, 202_nuruki_touya/techUPstudy_JavaScript課題/js/script_3_18.js, 202_nuruki_touya/techUPstudy_JavaScript課題/js/script_3_21.js
お疲れ様です！！！！
202_塗木統耶 JavaScript18~22課題提出致します！
お手隙で大丈夫ですのでご確認お願いいたします...!
=> 202_塗木統耶 JavaScript18~22課題提出

202_nuruki_touya/techUPstudy_JavaScript課題/css/style.css, 202_nuruki_touya/techUPstudy_JavaScript課題/index_3_23.html, 202_nuruki_touya/techUPstudy_JavaScript課題/js/script_3_23.js
お疲れ様です！
JavaScript23課題提出させていただきます！！
若干手抜き感ありますがご愛敬くださいませ...!!
お手隙でご確認お願いいたします！
=> 202_塗木統耶 JavaScript23課題提出

188_takahashi_mei/CSS_html/index_2_1.html
課題を提出します。【L2_1.HTMLを作成しよう！】
課題の学習が前後していました。
HTMLの学習をとばしてCSS基礎から始めていたようです。
すでに終了した課題や進捗に関しては、techUPのHPに入力しております。
申し訳ございませんが、ご確認お願いいたします。
=> 高橋芽愛　L2_1.HTMLを作成しよう！

216_ueda_arisa/index_1.php
お疲れさまです。
G-3の課題を提出させていただきます。
ご確認のほどよろしくお願いいたします。
=> G-3 上田有紗　GitHubを使った作業　課題提出

188_takahashi_mei/CSS_html/index_2_2.html
課題を提出します。
【HTML/CSS  ２文章構造をマークアップする】
ご確認お願いします。
=> 高橋芽愛　L2_2 文章構造をマークアップする

211_kawayama_saya/level7_3_table_study.sql
=> 川山紗弥　 P-6の課題提出

188_takahashi_mei/CSS_html/index_2_3.html
課題を提出します。「L2_3 タグと要素」
ご確認お願いします！
=> 高橋芽愛　L2_3 タグと要素

216_ueda_arisa/Coffee.php, 216_ueda_arisa/Dripper.php, 216_ueda_arisa/IDrip.php, 216_ueda_arisa/Patient.php, 216_ueda_arisa/Person.php, 216_ueda_arisa/Tea.php, 216_ueda_arisa/index.php, 216_ueda_arisa/index4_2.php, 216_ueda_arisa/php-7-answer.txt
お疲れさまです。
P4-1とP4-2の課題を再提出いたします。
ご確認のほどよろしくお願いいたします。
=> P4-1.2 上田有紗 課題再提出

214_tsugane_saki/H-1/index_2_1.html
=> H-1 津金沙季　HTMLを作成しよう！

214_tsugane_saki/H-6/index_2_6.html
=> H-6 津金沙季　テーブルの表現

214_tsugane_saki/H-8/index_2_8.html
=> H-8 津金沙季　入力部品を使う

214_tsugane_saki/H-9/index_2_9.html
=> H-9 津金沙季　formタグの意味と使い方

214_tsugane_saki/H-10/index_2_10.html
=> H-10 津金沙季　総合HTML課題

214_tsugane_saki/C-1/index_2_11.html
=> C-1 津金沙季　CSS基礎

214_tsugane_saki/C-2/index_2_12.html
お疲れ様です。
C-2課題提出いたします。
右下へずらしていく重なりが難しかったです。余白で調整してみました。
=> C-2　津金沙季　CSSスタイルの継承

214_tsugane_saki/H-5/index_2_5.html
=> H-5 津金沙季　divとspanの違い

214_tsugane_saki/H-7/index_2_7.html
お疲れ様です。
H-7課題提出いたします。
はじめ<p>タグで作成したのですが、<p>タグだとどう頑張ってもフォームの左側が揃わなかったので、tableを使用して作成してみました！
なんとかそれっぽくなったかなと思います！
=> H-7 津金沙季　フォーム部品について

214_tsugane_saki/C-5/index_2_15.html
=> C-5 津金沙季　初期値について、ボックスモデルと指定プロパティ

214_tsugane_saki/C-4/index_2_14.html
=> C-4 津金沙季　スタイルを設定しよう

214_tsugane_saki/C-6/index_2_16.html
お疲れ様です。
C-6課題提出いたします。
なかなか上下左右中央揃えにならず時間がかかりました。
=> C-6 津金沙季　要素に絶対配置する

214_tsugane_saki/C-7/index_2_17.html
=> C-7 津金沙季　属性セレクターを使う

214_tsugane_saki/C-13/index_2_23.html
=> C-13 津金沙季　グリッドの設定

214_tsugane_saki/C-8/index_2_18.html
=> C-8 津金沙季　疑似要素、疑似クラス

214_tsugane_saki/C-11/index_2_21.html
=> C-11 津金沙季　アニメーションを使う

214_tsugane_saki/C-12/index_2_22.html
=> C-12 津金沙季　レスポンシブwebデザイン

188_takahashi_mei/CSS_html/index_2_6.html
課題を提出します。「H-6.リスト, テーブルの表現」
ご確認お願いいたします。
=> 高橋芽愛　H-6.リスト, テーブルの表現

214_tsugane_saki/C-14/index_2_24.html
=> C-14 津金沙季　CSS変数の宣言

188_takahashi_mei/CSS_html/index_2_7.html
課題を提出します。【H-7.フォーム部品について】
ご確認お願いします。
=> 課題提出　高橋芽愛　H-7.フォーム部品について

214_tsugane_saki/J-1/index_3_4.html
=> J-1 津金沙季　J-1.JavaScriptを学ぼう

214_tsugane_saki/J-2/index_3_5.html
=> J-2 津金沙季　J-2JavaScript演算

214_tsugane_saki/J-4/index_3_7.html
=> J-4　津金沙季　条件分岐

214_tsugane_saki/J-5/index_3_8.html, 214_tsugane_saki/index_3_8.html
=> J-5 津金沙季　関数定義

214_tsugane_saki/J-6/index_3_9.html
=> J-6　津金沙季　配列計算

214_tsugane_saki/J-8/index_3_11.html
=> J-8 津金沙季　構文の使い方

214_tsugane_saki/J-9/index_3_12.html
お疲れ様です。
J-9課題提出致します。
ご確認をよろしくお願い対します。
=> J-9 津金沙季　オブジェクトの作り方

188_takahashi_mei/CSS_html/index_2_10.html
課題を提出します。H-10. 総合HTML課題
ご確認おねがいします。
=> 高橋芽愛　H-10. 総合HTML課題

214_tsugane_saki/J-15/index3_18.html
=> J-15 津金沙季　フォームの操作を理解しよう！

188_takahashi_mei/CSS_html/index_2_14.html
課題を提出します。L2-14 スタイルを設定しよう。　ご確認おねがいいたします！
=> 高橋芽愛　L2-14 スタイルを設定しよう

188_takahashi_mei/CSS_html/index_2_15.html
=> 高橋芽愛　HTML＿SCC C-5. 初期値について、ボックスモデルと指定プロパティ

188_takahashi_mei/CSS_html/index_2_17.html
課題を提出します。「C-7. 属性セレクターを使う」
ご確認お願いいたします！　
=> 高橋芽愛　C-7. 属性セレクターを使う

188_takahashi_mei/CSS_html/index_2_18.html
課題を提出します。C-8. 擬似要素、擬似クラス
ご確認お願いいたします。
=> 高橋芽愛　C-8. 擬似要素、擬似クラス

211_kawayama_saya/index_2_2.html
「H-2. 文章構造をマークアップする」の課題を提出しました。確認お願いします。
=> 川山紗弥　H-2課題提出：文章構造のマークアップ

156_ootsuka_ryousuke/index_2_8.html
夜分遅くに失礼します。
課題を提出します。
ご確認よろしくお願いします。
=> 大塚亮典 H8 入力部品を使う

156_ootsuka_ryousuke/index_2_9.html
お疲れ様です。
課題を提出します。
ご確認のほど宜しくお願いします。
=> 大塚亮典 H9 formタグ

156_ootsuka_ryousuke/index_2_10.html
=> 大塚亮典 H10 総合課題

207_morooka_takato/javascript/J-4 条件分岐/index_3_7.html
お疲れ様です。
J-4　課題提出いたしました
ご確認よろしくお願いします。
=> J-4 諸岡貴斗 条件分岐　課題提出

156_ootsuka_ryousuke/index_2_11.html
お疲れ様です。
修正したので再提出します。
ご確認のほど宜しくお願いします。
=> 大塚亮典 CSS基礎 修正再提出

188_takahashi_mei/CSS_html/index_2_24.html
課題を提出いたします！
【L2_24 CSS変数の宣言】
ご確認お願いいたします！
=> 高橋芽愛　L2_24 CSS変数の宣言

156_ootsuka_ryousuke/index_2_12.html
お疲れ様です。
課題を提出します。
ご確認のほど宜しくお願いします。
=> 大塚亮典 C2 CSSスタイルの継承

156_ootsuka_ryousuke/index_2_14.html
お疲れ様です。
課題を提出します。
確認のほど宜しくお願いします。
ひとつ前のディベロッパーツールの使用課題については
ページ内の埋め込み動画を見て、ブラウザで動作を確認しました。
=> 大塚亮典 C-5 CSSの設定 

207_morooka_takato/javascript/J-6. 配列計算/index_3_9.html
お疲れ様です。
J-6　課題提出いたしました。
ご確認の程、よろしくお願いします。
=> J-6 諸岡貴斗 配列計算　課題提出

156_ootsuka_ryousuke/index_2_15.html, 156_ootsuka_ryousuke/index_2_16.html
お疲れ様です。
課題を提出します。
ご確認を宜しくお願いします。
=> 大塚亮典 C-6. 要素を絶対配置する 

211_kawayama_saya/index_2_11.html
=> 川山紗弥　C-1　課題　CSSを記述したHTMLファイル

156_ootsuka_ryousuke/index_2_18.html
=> 大塚亮典 C-8. 擬似要素、擬似クラス

156_ootsuka_ryousuke/index_2_20.html
お疲れ様です。
課題を提出します。
ご確認を宜しくお願いします。
=> 大塚亮典 C-10.画像の配置

188_takahashi_mei/JS/index_3_6.html
課題を提出します。「J-3. JavaScriptデータ型の扱い」
ご確認おねがいいたします！
=> 高橋芽愛　J-3. JavaScriptデータ型の扱い

188_takahashi_mei/JS/index3_7.html
課題を提出します。「J-4. 条件分岐」
ご確認お願いいたします。
=> 高橋芽愛　J-4. 条件分岐

188_takahashi_mei/JS/index_3_8.html
課題を提出します。「J-5. 関数定義」
ご確認お願いいたします。
=> 高橋芽愛　J-5. 関数定義

188_takahashi_mei/JS/index_3_10.html
課題を提出します。「J-7. 要素の変更」
ご確認お願いいたします！
=> 高橋芽愛　J-7. 要素の変更

188_takahashi_mei/JS/index_3_11.html
　課題を提出します。「J-8. 構文の使い方」
ご確認おねがいします。
=> 高橋芽愛　J-8. 構文の使い方

156_ootsuka_ryousuke/index_2_24.html
お疲れ様です。
課題を提出します。
ご確認のほど宜しくお願いします。
=> 大塚亮典 C-14.CSS変数の宣言

188_takahashi_mei/JS/index_3_12.html
課題を提出します。「J-9. オブジェクトの作り方」
ご確認おねがいします！
=> 高橋芽愛　J-9. オブジェクトの作り方

188_takahashi_mei/JS/index_3_13.html
　課題を提出します。「J-10. 配列とオブジェクトの組み合わせ」
ご確認おねがいいたします！
=> 高橋芽愛　J-10. 配列とオブジェクトの組み合わせ

188_takahashi_mei/JS/index_3_14.html
課題を提出します。「J-11. いろんなメソッド」
ご確認お願いいたします！
=> 高橋芽愛　J-11. いろんなメソッド

188_takahashi_mei/JS/index_3_15.html, 188_takahashi_mei/JS/index_3_16.html, 188_takahashi_mei/JS/index_3_17.html, 188_takahashi_mei/JS/index_3_18.html, 188_takahashi_mei/JS/todolist.js
課題を提出します。ご確認お願いいたします！
J12「メソッドやクラスを使う」
　index_3_15.html
J13「DOM(Document Object Model)」
　index_3_16.html
J14「classList (DOM総合課題)」
　index_3_17.html  /  todolist.js
J15「フォームの操作を理解しよう！」
　index_3_18.html
=> 高橋芽愛　J12〜J15

174_yoshimi_misaki/H-3/index_2_3.html
=> 吉見美咲H3課題提出
